---
- name: Configure Minecraft Server
  hosts: minecraft
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jre-headless
        state: present

    - name: Create minecraft user
      user:
        name: minecraft
        system: yes
        create_home: yes
        shell: /bin/bash

    - name: Create minecraft directory
      file:
        path: /opt/minecraft
        state: directory
        owner: minecraft
        group: minecraft

    - name: Download Minecraft server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
        dest: /opt/minecraft/server.jar
        owner: minecraft
        group: minecraft
        mode: '0755'

    - name: Accept EULA
      copy:
        dest: /opt/minecraft/eula.txt
        content: "eula=true\n"
        owner: minecraft
        group: minecraft

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft
          ExecStart=/usr/bin/java -Xms1G -Xmx2G -jar server.jar nogui
          SuccessExitStatus=0 1
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started